PGGexoEN/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random

doc = """The English version of Public Goods Game with exogeneous threshold"""



class Constants(BaseConstants):
    name_in_url = 'PGGexoEN'
    players_per_group = 5
    num_rounds = 25

    endowment = c(55)
    efficiency_factor = 2 #step return
    cost_parameter_low = 1 #useless because no high/low players
    cost_parameter_high = 1 #ibid

    participation_fee = 0
    euro_per_point = 0.0651851851851852

    phase1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

    """"List of round numbers which are part of a distribution rule. """

    paying_phase1 = phase1

    """"The random round generator for the three payment periods to calculate money payoff."""

    thresholdexo = [125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125]
    """"The threshold levels in each round, starting in round 1 to round 25."""


class Subsession(BaseSubsession):

    def vars_for_admin_report(self):
        contributions = [p.contribution for p in self.get_players() if p.contribution is not None]
        return {
            'total_contribution': sum(contributions),
            'min_contribution': min(contributions),
            'max_contribution': max(contributions),
        }


class Group(BaseGroup):

    distribution_rule = models.CharField()
    threshold = models.CurrencyField()
    bonus = models.CurrencyField()
    total_contribution = models.CurrencyField()
    avg_contribution = models.CurrencyField()
    avg_payoff = models.CurrencyField()

    def set_distribution_rule(self):

            self.distribution_rule = 'Equal share of the bonus'


            """"This sets the distribution rule of each phase."""

    def set_threshold(self):
        for x in range(1, 26):
            if self.round_number == x:
                self.threshold = Constants.thresholdexo[x-1]

                """the variable x is every number between 1 and 13, excluding 13.
                    When the round number is equal to the variable x, it will look
                    up the element in thresholdexo list of threshold levels."""

    def set_payoffs(self):
        self.total_contribution = sum([p.contribution for p in self.get_players()])
        self.avg_contribution = self.total_contribution / Constants.players_per_group
        if self.total_contribution < self.threshold:
            self.bonus = 0
        else: self.bonus = Constants.efficiency_factor * self.threshold

        for p in self.get_players():
            if 'low' in p.role():
                p.value = (Constants.endowment - Constants.cost_parameter_low * p.contribution)
            else:
                p.value = (Constants.endowment - Constants.cost_parameter_high * p.contribution)

                """"p.value is the amount of points a player has left after contributing."""

        if self.distribution_rule == 'Equal payoff':
            if self.total_contribution < self.threshold:
                for p in self.get_players():
                    p.payoff_r = p.value
            else:
                for p in self.get_players():
                    p.payoff_r = (sum([p.value for p in self.get_players()]) + self.bonus)\
                                 / Constants.players_per_group

                    """"When threshold is met, payoff is calculated by summing the p.values,
                        adding them to the bonus, and dividing it by the amount of players 
                        per group (4 in this case)"""

                    p.check_r = p.payoff_r - p.value
                    if any(p.check_r < 0 for p in self.get_players() if p.check_r is not None):
                        self.distribution_rule = 'Equal share of the bonus exception'
                        p.payoff_r = p.value + (self.bonus / Constants.players_per_group)

                    """"An exception to the Equal payoff occurs when p.payoff_r is less
                        than p.value, resulting in a value loss for a player. In that case
                        the distribution rule is adjusted to equal share of the bonus"""

        else:
            if self.total_contribution < self.threshold:
                for p in self.get_players():
                    p.payoff_r = p.value
            else:
                for p in self.get_players():
                    p.payoff_r = p.value + (self.bonus / Constants.players_per_group)

                    """"Equal share of the bonus is calculated by adding the individual's p.value
                     with an equal share of the bonus, if the threshold is met."""

        self.avg_payoff = sum([p.payoff_r for p in self.get_players()]) / Constants.players_per_group





class Player(BasePlayer):

    def role(self):
        if self.id_in_group in [1, 2]:
            return 'low'
        else:
            return 'high'

    contribution = models.CurrencyField(
        min=0, max=Constants.endowment,
        doc="""The amount contributed by the player.""",
    )

    value = models.CurrencyField(
        doc=""""The player's individual payoff before bonus is taken into account."""
    )

    prule = models.PositiveIntegerField(
        choices=[
            [0, 'Equal share of the bonus'],
            [1, 'Equal payoff']
        ],
        widget=widgets.RadioSelect(),
        doc=""""The player's vote for distribution rule in phase 3."""
    )


    payoff_r = models.CurrencyField(
        doc=""""payoff in a certain round"""
    )

    check_r = models.FloatField(
        doc=""""The check for Equal payoff viability, if negative value,
         it's not viable"""
    )

    heard_PGG = models.BooleanField(
        label="Have you previously heard of a “public goods game”? ",
        choices=[
            [True, 'Yes'],
            [False, 'No'],

        ],
        widget=widgets.RadioSelectHorizontal
    )

    fairness = models.PositiveIntegerField(
        label="What is a 'fair' contribution in the public good? (number)",
        min=0, max=Constants.endowment
    )

    fairness_explore = models.TextField(
        label="Are you concerned about 'fairness' in making your contribution decision? Please elaborate briefly on your idea of 'fairness' and how important it is to you"
    )

    reasons_explore = models.TextField(
        label="Please state the reasons for your contributions. Elaborate on your motives, why did you make the decisions you did? Which of the reasons was the most important? "
    )


    business = models.BooleanField(
        label = "Do you or did you study one of the following programmes: "
                 "Economics and Business Administration, BSc; Erhvervsøkonomi, HA; Erhvervsøkonomi med tilvalg; Erhvervsøkonomi og erhvervsret(HA(jur.)); Economics and Business Administration, MSc (cand.merc); Marketing and Management Communication?",
        choices=[
            [True, 'Yes'],
            [False, 'No'],

        ],
        widget=widgets.RadioSelectHorizontal
    )
    economics = models.BooleanField(
        label = "Do you or did you study one of the following programmes: Økonomi; Politik og økonomi; Matematik-økonomi?",
        choices=[
            [True, 'Yes'],
            [False, 'No'],

        ],
        widget=widgets.RadioSelectHorizontal
    )
    earnings_phase1 = models.PositiveIntegerField()
    paid = models.PositiveIntegerField()


    def set_payoff(self):
        # must add all rounds one by one to self.earnings_phase1
        self.earnings_phase1 = self.in_round(1).payoff_r+self.in_round(2).payoff_r+self.in_round(3).payoff_r+self.in_round(4).payoff_r+self.in_round(5).payoff_r+self.in_round(6).payoff_r+self.in_round(7).payoff_r+self.in_round(8).payoff_r+self.in_round(9).payoff_r+self.in_round(10).payoff_r+self.in_round(11).payoff_r+self.in_round(12).payoff_r+self.in_round(13).payoff_r+self.in_round(14).payoff_r+self.in_round(15).payoff_r+self.in_round(16).payoff_r+self.in_round(17).payoff_r+self.in_round(18).payoff_r+self.in_round(19).payoff_r+self.in_round(20).payoff_r+self.in_round(21).payoff_r+self.in_round(22).payoff_r+self.in_round(23).payoff_r+self.in_round(24).payoff_r+self.in_round(25).payoff_r
        self.payoff = self.earnings_phase1
        self.paid = (self.payoff * Constants.euro_per_point) + Constants.participation_fee

        """"The calculation of the payoffs during the periods
            and total earnings as well as the to be paid amount."""

PGGexoEN/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.api

import otree.api
from otree.api import Currency as c, currency_range

class Page(otree.api.Page):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):


    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

PGGexoEN/views.py
from . import models
from ._builtin import Page, WaitPage
from otree.api import Currency as c, currency_range
from .models import Constants

class GroupingWaitPage(WaitPage):
    group_by_arrival_time = True

    def is_displayed(self):
        return self.round_number == 1

    body_text = "Please wait"




class IntroWaitPagePhase1(WaitPage):
    """WaitPage to continue when everyone is ready for the next phase"""
    def is_displayed(self):
        return self.round_number in Constants.phase1

    def after_all_players_arrive(self):
        self.group.set_distribution_rule()
        self.group.set_threshold()

    body_text = "Please wait"



class DistributionRuleAnnounce(Page):
    timeout_seconds = 60


class Contribute(Page):
    """Players have to decide how much points to contribute."""
    form_model = models.Player
    form_fields = ['contribution']

 #   def set_threshold(self):
  #      return


class ResultsWaitPage(WaitPage):
    """"WaitPage to calculate the the payoffs."""
    def after_all_players_arrive(self):
        self.group.set_payoffs()

    body_text = "Please wait"


class Results(Page):
    """Players payoff: How much each has earned"""
    timeout_seconds = 300


    def vars_for_template(self):
        return {
            'total_earnings': self.group.total_contribution * Constants.efficiency_factor,
        }


class EarningsWaitPage(WaitPage):
    def is_displayed(self):
        return self.round_number == Constants.num_rounds

    def after_all_players_arrive(self):
        for p in self.group.get_players():
            p.set_payoff()

    body_text = "Please wait"


class Earnings(Page):
    def is_displayed(self):
        return self.round_number == Constants.num_rounds

class Post_Questionnaire(Page):
    """First part of post coital questionnaire"""
    def is_displayed(self):
        return self.round_number == Constants.num_rounds
    form_model = models.Player
    form_fields = ['business', 'economics', 'heard_PGG', 'reasons_explore']

class Post_Questionnaire_2(Page):
    """Second part of post coital questionnaire"""
    def is_displayed(self):
        return self.round_number == Constants.num_rounds
    form_model = models.Player
    form_fields = ['fairness', 'fairness_explore']

class Thank_you(Page):
    def is_displayed(self):
        return self.round_number == Constants.num_rounds



page_sequence = [
    GroupingWaitPage,
    IntroWaitPagePhase1,
    DistributionRuleAnnounce,
    Contribute,
    ResultsWaitPage,
    Results,
    EarningsWaitPage,
    Earnings,
    Post_Questionnaire,
    Post_Questionnaire_2,
    Thank_you
]

PGGexoEN/templates/PGGexoEN/AdminReport.html
<table class="table">
    <tr>
        <th>Average contribution</th>
        <td>{{ avg_contribution }}</td>
    </tr>
    <tr>
        <th>Min contribution</th>
        <td>{{ min_contribution }}</td>
    </tr>
    <tr>
        <th>Max contribution</th>
        <td>{{ max_contribution }}</td>
    </tr>
</table>

PGGexoEN/templates/PGGexoEN/Contribute.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}



{% block title %}
    Round {{ group.round_number }} of {{ Constants.num_rounds }}
{% endblock %}

{% block content %}


    <hr> </hr>

    <h4><b>Choose your contribution</b></h4>

    <p>
        The threshold is: <b>{{ group.threshold }}</b>. <br>
        You income is: <b>55 points</b><br>
    </p>

    <p> The distribution rule is <b>{{ group.distribution_rule }}</b>.<br>
        Now you can make a decision on <b>your contribution</b> to the group project for this round.<br>
        Please submit your contribution in integers, <b> between 0 and 55 points </b>.
    </p>


    <hr> <hr>


    {% formfield player.contribution with label="My contribution to the group project is:" %}


<hr> </hr>

    {% next_button %}

<hr> </hr>
    <p> <i>Help: If you have vital questions, you can email the researcher (Jedrzej) at 201811497@post.au.dk</i></p>
{% endblock %}

PGGexoEN/templates/PGGexoEN/DistributionRuleAnnounce.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Round Announcement
{% endblock %}

{% block content %}

<p> You are about to play Round <b>{{ subsession.round_number }}</b>.<br></p>
<p><span style="font-weight: 400;">A short reminder of the rules. All of the players receive equal income and an equal share of the bonus if the threshold is reached. If the threshold is not reached, the contributions do not get returned to their owners.</span></p>
<p><span style="font-weight: 400;"> If total contributions in your group equal 125 points or more and you have contributed X, your earnings from this round will be: </span><em><span style="font-weight: 400;">&nbsp;</span></em><em><span style="font-weight: 400;">Your earnings = your income (55 points)&nbsp; &ndash; your contribution(X points) + additional points (50 points)</span></em></p>
<p><span style="font-weight: 400;">If, on the other hand, total contributions in your group equal less than 125 points and you have contributed X, your earnings will be your income minus your contribution, because there is no refund:&nbsp; </span><em><span style="font-weight: 400;">Your earnings = your income (55 points)&nbsp; &ndash; your contribution(X points)</span></em></p>
<hr> </hr>

    {% next_button %}

<hr> </hr>
    <p> <i>Help: If you have vital questions, you can email the researcher (Jedrzej) at 201811497@post.au.dk</i></p>
{% endblock %}

PGGexoEN/templates/PGGexoEN/Earnings.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}


{% block title %}
    Total Earnings
{% endblock %}

{% block content %}

<hr> </hr>


<p> Your cumulative payoff in <b> 25 rounds </b> was: <b>{{ player.earnings_phase1 }} points </b><br>

    </p>

    <p>
        1 point (token) = <b>{{ Constants.euro_per_point }} DKK.</b><br>
        Your total earnings are: <b>{{ player.paid }} DKK</b>.
    </p>

    <p> Please click on the next button to continue to a short survey.</p>

<hr> </hr>

    {% next_button %}


<hr> </hr>
    <p> <i>Help: If you have vital questions, you can email the researcher (Jedrzej) at 201811497@post.au.dk</i></p>
{% endblock %}

PGGexoEN/templates/PGGexoEN/Phase1Intro.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Comprehension test
{% endblock %}

{% block content %}

<p> <b> In this section we will ask you three questions meant to test your familiarity with the instructions. </b> <br>
</p>

{% formfield player.comprehension1 %}


{% formfield player.comprehension2 %}


{% formfield player.comprehension3 %}

<hr> </hr>

    {% next_button %}

<hr> </hr>
    <p> <i>Help: If you have any questions, please raise your hand.</i></p>
{% endblock %}

{% block styles %}
    <style>

            .errorlist {
                display: none;
            }

    </style>
{% endblock %}

PGGexoEN/templates/PGGexoEN/Post_Questionnaire.html
{% extends "global/Page.html" %}
{% load otree %}

{% block title %}
Questionnaire part 2
{% endblock %}

{% block content %}
<p> <strong>Please take at least 5 minutes to answer the following questions. </strong></p>


{% formfields %}

{% next_button %}

<hr> </hr>
    <p> <i>Help: If you have vital questions, you can email the researcher (Jedrzej) at 201811497@post.au.dk</i></p>
{% endblock %}

PGGexoEN/templates/PGGexoEN/Post_Questionnaire_2.html
{% extends "global/Page.html" %}
{% load otree %}

{% block title %}
Questionnaire part 2
{% endblock %}

{% block content %}
<p> <strong>Please take at least 5 minutes to answer the following questions. </strong></p>


{% formfields %}

{% next_button %}

<hr> </hr>
    <p> <i>Help: If you have vital questions, you can email the researcher (Jedrzej) at 201811497@post.au.dk</i></p>
{% endblock %}

PGGexoEN/templates/PGGexoEN/Results.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Round {{ subsession.round_number }} of {{ Constants.num_rounds }}
{% endblock %}

{% block content %}
<hr> </hr>
    <p> <i>Scroll to the right to see the whole table.</i></p>


       <table class="table">
        <tr>
            <th>Round</th>
            <th>Threshold</th>
            <th>Contribution Player 1</th>
            <th>Contribution Player 2</th>
            <th>Contribution Player 3</th>
            <th>Contribution Player 4</th>
            <th>Contribution Player 5</th>
            <th>Average contribution</th>
            <th>Payoff Player 1</th>
            <th>Payoff Player 2</th>
            <th>Payoff Player 3</th>
            <th>Payoff Player 4</th>
            <th>Payoff Player 5</th>
            <th>Average payoff</th>
        </tr>
        <tr>
                <td> {{ subsession.round_number }}</td>
                <td> {{ group.threshold }}</td>
            {%  for p in group.player_set.all %}
                <td> {{ p.contribution }}</td>
            {% endfor %}
                <td> {{ group.avg_contribution }}</td>
            {% for p in group.player_set.all %}
                <td> {{ p.payoff_r }}</td>
            {% endfor %}
                <td>{{ group.avg_payoff }}</td>
        </tr>
    </table>


    <hr> </hr>
    <h4> Summary of contributions and profits this round:</h4>

        <table class="table-condensed" style="width:500px; margin-top:20px;">
        <tr><td>The distribution rule: </td><td> <b>{{ group.distribution_rule }}</b></td></tr>
        <tr><td>The group threshold: </td><td><b>{{ group.threshold }}</b></td></tr>
        <tr><td>Total group contribution: </td><td><b>{{ group.total_contribution }}</b></td></tr>
        <tr><td>Total group bonus: </td><td><b>{{ group.bonus }}</b></td></tr>
        <tr><td>Average contribution in your group: </td><td><b>{{ group.avg_contribution }}</b></td></tr>
        <tr><td>Your contribution: </td><td><b>{{ player.contribution}}</b></td></tr><tr>
        <tr><td>Your payoff: </td><td><b>{{ player.payoff_r }}</b></td></tr>


    </table>

<hr> </hr>

    {% next_button %}

<hr> </hr>
    <p> <i>Help: If you have vital questions, you can email the researcher (Jedrzej) at 201811497@post.au.dk </p>
{% endblock %}

PGGexoEN/templates/PGGexoEN/Thank_you.html
{% extends "global/Page.html" %}

{% load otree_tags staticfiles %}

{% block title %}
Thank you for participating in this experiment! Stay home and continue being awesome :)
{% endblock %}


{% block content %}

<hr> </hr>
    <p> <i>Help: If you have any questions, you can email the researcher (Jedrzej) at 201811497@post.au.dk. The payments will be sent as soon as possible.</i></p>
{% endblock %}